dist: trusty
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.10
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
- "~/tfbin/terraform init -upgrade -input=false"
- pushd meta && ~/tfbin/terraform init -upgrade -input=false && popd
script:
- pushd meta && ~/tfbin/terraform fmt -write=false -diff=true -check && popd
- pushd meta && ~/tfbin/terraform plan -detailed-exitcode -input=false && popd
- "~/tfbin/terraform fmt -write=false -diff=true -check"
- "~/tfbin/terraform plan -detailed-exitcode -input=false"
notifications:
  email: false
  slack:
    secure: WyaNCIf/m/ExMOUYdX3+acDfLZ+e3olMR8lVR0jFIJh51/C+iOoLUEn4cenvpT/HHu5O+pzPcykF5275LYQk4CGuy3qLC28ic13b7bpoXQC+WSC0TWBr0yKxI2dhFy9CdcxsJPRFtAhDBiomOi1EJ2FGUA/x7rkATV4BPhS2oV8KwwEhvOq421khzd1tPaBhZxZWPNTmp+/gIVT5fvoFSKHaR3hh9UFDJ8hzAU9rygnapnCTvAt7E7Dz3J7z5pizw5OXxsXxKe8BNcYQumT4g3mK2bYz1GzHoQydsbBM9oGzggsKkW95u58StpvQ0YA0NCOYH7DDJNj4AVDMh7tlhtwAnGASjYsnzVqoySfma7Cu9UVGO82xgTDcPEW2sG7E2XQ4e0kVVaoYI/tBMJZyHEdGP3E4DpeikIX68G79jdN0ZTWugAkxn77qwQ3KTw/LMyfWyLFlYCOoj6Vu7rIi5Syxn5wB+aQVN89HCH4BNAdkos+M4qIY4c+32Wie0pFr8ZaDSsuxVT8ZUOSGotnSbKth6JoSTDSMjGVajXuSOwyV2Vv3AFilacOhyABLpS/Z3UH26yhaVob9mT38y57bMmmLK+psmV/1dWnAM9KIvKrhIop4RBQ0CBcL7fT6IRs8zccRhPC+eHufqDyvRs/S2BtdQ61TixbphNUZWHQa4bY=
